spring:
  flyway:
    locations: classpath:/data/dev/migrations
  jpa:
      show-sql: true
      hibernate:
          ddl-auto: validate
#          use-new-id-generator-mappings: false
      properties:
          hibernate:
            dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
      tomcat:
          max-active: 50
          max-idle: 20
          max-wait: 20000
          min-idle: 15
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reservation?useUnicode=yes&characterEncoding=UTF-8
      username: reservationuser
      password: Reserv1!pass
